### ISSUE TITLE
won't open

### ISSUE THREAD

**Issue by Dherff** [israpps/PAKerUtility#3]
Please help me open this program. I tried opening it simply by clicking on it - won't work. Then I tried cmd - no use. Afterwards I enabled admin mode for cmd - still nothing opens. I even added directory to cmd command list but still no results. What am I doing wrong? I'm just not a programmer and I simply need this tool to open some files for a game. Win10

**Comment by israpps** [comment]
Hi.

1) this program is a command line tool
2) AFAIK no video game uses this file format...

**Comment by israpps** [comment]
Program sintax:

Create PAK archive
```bash
PAKerUtility.exe -c <PAK file> <Manifest file>
```

Extract PAK archive
```bash
PAKerUtility.exe -x <PAK file>
```

List contents
```bash
PAKerUtility.exe -l <PAK file>
```

Create manifest 
```bash
PAKerUtility.exe -m <PAK file> <Manifest file>
```
